-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('VISITOR', 'USER', 'COLLECTOR', 'COMMUNITY_VALIDATOR', 'INSTITUTIONAL_VALIDATOR', 'ADMIN');

-- CreateEnum
CREATE TYPE "ConfidentialityLevel" AS ENUM ('PUBLIC', 'RESTRICTED', 'CONFIDENTIAL');

-- CreateEnum
CREATE TYPE "EthnoDataStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'COMMUNITY_VALIDATION', 'INSTITUTIONAL_VALIDATION', 'PUBLISHED', 'REJECTED', 'ARCHIVED');
